### PR TITLE
Add rss generation script

### LINKED ISSUE #2: Adding an RSS feed
Hello, I'm a reader of your great blog posts! One thing I have always felt inconvenient was that I don't have any mechanism to get updates unless I frequently check.
Would it be possible to have an RSS feed of the posts? I guess you aren't writing the posts in pure HTML - if it's possible to push the code (whether it's Jekyll or  used for writing the posts, I'm more than eager to help you adding the feed. Thanks!

### PR DESCRIPTION
**Pull request by goranmoomin**
This PR fixes #2.

### CODE REVIEW

**Comment by goranmoomin** [comment]
With this PR, the RSS feed will look like this in [NetNewsWire](https://ranchero.com/netnewswire/):
Screen Shot 2020-06-05 at 11 00 21 AM

And this is an example of the JS script alert:
Screen Shot 2020-06-05 at 11 00 33 AM

The generated RSS feed would be valid (checked with the [W3C feed validator](https://validator.w3.org/feed/)). (You will probably have to ignore the 'recommendations' part - it's usually just false alarms.)

Screen Shot 2020-06-05 at 11 01 31 AM

**Comment by leontrolski** [comment]
Lovely stuff, thanks a load!

**Comment by leontrolski** [comment]
When I run the script locally, I get all the timestamps with +01:00, (but otherwise identical), you reckon this is an issue @pcr910303, or shall I change to always have +00:00?

**Comment by leontrolski** [comment]
```
TZ=UTC git log -1 --format='%ad' --date=iso-local
```
looks like maybe the nicest

**Comment by goranmoomin** [comment]
Well, the [RSS `pubDate` element uses the RFC822 format](https://validator.w3.org/feed/docs/rss2.html#ltpubdategtSubelementOfLtitemgt) (the RFC link is dead in the W3C spec) — which is superseded by RFC2822. That’s why I used RFC2822. I’m not sure about the ISO formats, but I think it’ll be fine. At least it looks fine ok my phone :-)

image

**Comment by goranmoomin** [comment]
Oh, I misunderstood the comment — due to the reasons I mentioned earlier, I wouldn’t recommend you to switch to a non-RFC2822 format (even though I think most readers will understand them).  

I can’t understand why the timestamps print 01:00, it works on my machine :-(

**Pull request merged**
